name: chuckegerton.com
favicon: null
layout_spectrum: 0.677307270700112
typography_spectrum: 0.6010575138498098
title: 'Chuck Egerton '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262127'
    - '#ddd3cb'
    - '#f3eeea'
    - '#aea4a2'
    - '#928b93'
  brandStrength: 0.5
  lightness: 0.7524071906227618
  saturation: 0.5421840210910887
  rhythmicContrast: 0.75
purpose: []
